name: Build Docker Images from project

on: [workflow_dispatchs]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker images
      run: |
        docker build -t justas/backEndImagee:latest ./backend
        docker build -t justas/frontEndImage:latest ./frontend

 
