name: Build Docker Images from project

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker images
      run: docker-compose build -t justas/testimage:latest ./backend
 
 version: '3.8'